#!/usr/bin/env bash
#
# regenerate-skill-yaml.sh — regenerate skill.yaml skeletons from SKILL.md.
#
# Each skill in this plugin has two files:
#
#   skills/<name>/SKILL.md     the prose source of truth (human-written)
#   skills/<name>/skill.yaml   a state-machine skeleton generated by
#                              atomic-gates' import_skill.py converter
#
# The skill.yaml files are meant to be regenerated whenever the SKILL.md
# changes. They are committed so users installing just this plugin (without
# atomic-gates) don't need to run anything, and so anyone reading the repo
# can see the mechanical output of the converter side-by-side with the
# prose.
#
# Prerequisites:
#   - atomic-gates plugin checkout available at the path set below, OR
#     passed via ATOMIC_GATES_ROOT env var.
#   - python3 with pyyaml in PATH.
#
# Usage:
#   ./scripts/regenerate-skill-yaml.sh
#   ATOMIC_GATES_ROOT=/path/to/atomic-gates ./scripts/regenerate-skill-yaml.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default path to the atomic-gates checkout (used to find import_skill.py).
# Override with ATOMIC_GATES_ROOT env var if your checkout lives elsewhere.
ATOMIC_GATES_ROOT="${ATOMIC_GATES_ROOT:-$HOME/Code/atomic-gates}"
CONVERTER="$ATOMIC_GATES_ROOT/lib/import_skill.py"

if [[ ! -f "$CONVERTER" ]]; then
  echo "Error: converter not found at $CONVERTER" >&2
  echo "Set ATOMIC_GATES_ROOT to your atomic-gates checkout." >&2
  exit 1
fi

cd "$REPO_ROOT"

count=0
for skill_dir in skills/*/; do
  skill_name="$(basename "$skill_dir")"
  source_md="$skill_dir/SKILL.md"
  target_yaml="$skill_dir/skill.yaml"

  if [[ ! -f "$source_md" ]]; then
    echo "  $skill_name: no SKILL.md, skipping"
    continue
  fi

  python3 "$CONVERTER" "$source_md" -o "$target_yaml"
  count=$((count + 1))
done

echo ""
echo "Regenerated $count skill.yaml file(s)."
echo "The skeletons are first drafts — review each one, prune meta-headings,"
echo "refine agent_prompts, and add output_schemas where you want structured"
echo "validation. See docs/authoring-state-machines.md in atomic-gates for"
echo "the full workflow."
