#!/usr/bin/env bash
#
# regenerate-skill-yaml.sh — regenerate skill.yaml skeletons from SKILL.md.
#
# Each skill in this plugin has two files:
#
#   skills/<name>/SKILL.md     the prose source of truth (human-written)
#   skills/<name>/skill.yaml   a state-machine definition consumed by the
#                              atomic-gates runner
#
# Most skills ship a skill.yaml that was AUTO-GENERATED by atomic-gates'
# lib/import_skill.py converter from SKILL.md. These are raw skeletons:
# running this script regenerates them and overwrites any edits.
#
# Some skills have been "promoted" — their skill.yaml has been refined by
# hand into a production state machine (output_schema per state, when
# conditions on transitions, schemas/ directory for JSON Schemas).
# Regenerating those would destroy the refinement. They are listed in
# PROMOTED below and skipped by default.
#
# To regenerate a promoted skill anyway (e.g. after changing its SKILL.md):
#   FORCE_PROMOTED=1 ./scripts/regenerate-skill-yaml.sh
#
# Prerequisites:
#   - atomic-gates plugin checkout available at the path set below, OR
#     passed via ATOMIC_GATES_ROOT env var.
#   - python3 with pyyaml in PATH.
#
# Usage:
#   ./scripts/regenerate-skill-yaml.sh
#   ATOMIC_GATES_ROOT=/path/to/atomic-gates ./scripts/regenerate-skill-yaml.sh
#   FORCE_PROMOTED=1 ./scripts/regenerate-skill-yaml.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default path to the atomic-gates checkout (used to find import_skill.py).
# Override with ATOMIC_GATES_ROOT env var if your checkout lives elsewhere.
ATOMIC_GATES_ROOT="${ATOMIC_GATES_ROOT:-$HOME/Code/atomic-gates}"
CONVERTER="$ATOMIC_GATES_ROOT/lib/import_skill.py"

# Skills whose skill.yaml has been refined by hand. These are NOT regenerated
# from SKILL.md by default to preserve the hand-edits. Set FORCE_PROMOTED=1
# to regenerate them anyway (destroys refinements).
PROMOTED=(
  validate-issue
  review-pr
)

FORCE_PROMOTED="${FORCE_PROMOTED:-}"

if [[ ! -f "$CONVERTER" ]]; then
  echo "Error: converter not found at $CONVERTER" >&2
  echo "Set ATOMIC_GATES_ROOT to your atomic-gates checkout." >&2
  exit 1
fi

cd "$REPO_ROOT"

is_promoted() {
  local name="$1"
  for p in "${PROMOTED[@]}"; do
    [[ "$p" == "$name" ]] && return 0
  done
  return 1
}

count=0
skipped=0
for skill_dir in skills/*/; do
  skill_name="$(basename "$skill_dir")"
  source_md="$skill_dir/SKILL.md"
  target_yaml="$skill_dir/skill.yaml"

  if [[ ! -f "$source_md" ]]; then
    echo "  $skill_name: no SKILL.md, skipping"
    continue
  fi

  if is_promoted "$skill_name" && [[ -z "$FORCE_PROMOTED" ]]; then
    echo "  $skill_name: promoted (hand-refined), skipping — set FORCE_PROMOTED=1 to override"
    skipped=$((skipped + 1))
    continue
  fi

  python3 "$CONVERTER" "$source_md" -o "$target_yaml"
  count=$((count + 1))
done

echo ""
echo "Regenerated $count skill.yaml file(s); $skipped skipped (promoted)."
echo "Raw skeletons are first drafts — review each, prune meta-headings,"
echo "refine agent_prompts, and add output_schemas where you want structured"
echo "validation. See docs/guides/refining-skeletons.md in atomic-gates for"
echo "the full workflow. When a skill reaches production quality, add its"
echo "name to the PROMOTED array in this script so it isn't regenerated."
